import { GetServerSideProps } from "next";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  data: string
};

export default function Home(props: { hello: Props[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.h1}>Next.js App</h1>
        <div>
          {
            props.hello.map((x: Props, index: number) => {
              return <li key={index}>
                {x.data}
              </li>
            })
          }
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(`http://localhost:3000/api/hello`);
  const hello = await res.json() as Props[];

  return { props: { hello } };
}
